### ISSUE TITLE
Unable to convert Integer back to String.

### ISSUE THREAD

**Issue by daimajia** [aicodes/idea-plugin#2]
![image](https://cloud.githubusercontent.com/assets/2503423/22578422/a24e77a8-ea03-11e6-8f81-4f6af3c34f6f.png)

BTW.
Thanks for working on this project and opening it source. Looking forward to a success on this project.

**Comment by xuy** [comment]
@daimajia  Thanks for using the tool and reporting bugs.

I retrained the AI for processing queries, now it has better quality. The issue is fixed. (see attached graph).
<img width="344" alt="fix" src="https://cloud.githubusercontent.com/assets/1151720/22636542/d50c1396-ebf0-11e6-95ae-c8503f80e832.png">

Will file a separate bug on not re-using the "result" variable.
